[server]
headless = true
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#2563EB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"

[runner]
magicEnabled = true
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "auto"
